### ISSUE TITLE
New/extended query syntax

### ISSUE THREAD

**Issue by feffes** [algebraicdb/algebraicdb#4]
There was some talk about extending/changing the query syntax majorly to better accomodate sum and product types. 
There was a suggestion to use pattern matching as the primary selector,

tab: 

| col1(int) | col2(int) |
|-----------|-----------|
| 1         | 4         |
| 1         | 4         |
| 2         | 5         |

Example
```sql
select * from tab where col1 = 1; 
```
Becomes 
```sql
select (col1: 1) col2 from tab
```
Both return

| col1(int) | col2(int) |
|-----------|-----------|
| 1         | 4         |
| 1         | 4         |

while 

```sql
select (col1: 1) _ from tab
```
returns

| col1(int) |
|-----------|
| 1         |
| 1         |

I feel like I'm forgetting something at the moment, like something about which columns should be extracted depending on the match but  it's 00.24 big sleep time

**Comment by feffes** [comment]
We want to support:
```sql
select pattern from table ;
select pattern from table where condition ;
insert vals into table ;
update table set col=val  where condition ;
delete table where condition ;
```

**Comment by feffes** [comment]
The grammar is being developed on branch `grammar`

**Comment by hulthe** [comment]
Postgres has a fairly readable grammar in the docs, will probably be useful.
https://www.postgresql.org/docs/12/sql-select.html

**Comment by hulthe** [comment]
Here is an additional example of the pattern matching we discussed.
Given the following sum-type:
```haskell
Example = Val1 Int Int | Val2 String
```

And a table containing said sum-type:

| i::Int                      | e::ExampleSum |
| ----------------------- | --------------------- |
| 1                           | Val1 42 20         |
| 2                           | Val2 "hello"       |
| 3                           | Val1  0 99         |

We could construct the following query:
```sql
SELECT PATTERN (i, e: Val2 str, e) FROM our_table;
```

Output:

| i::Int | str::String | e::ExampleSum |
| --- | --- | --- |
| 2 | "hello" | Val2 "hello" |

In this example, the value of `e` is destructured in the pattern `e: Val2 str`. A new identifier `str` is then bound to the string value of `Example::Val2`. This means that only rows where `e` is of the variant `Val2` is returned.

**Comment by feffes** [comment]
@hulthe Taking into account `WHERE` conditionals, it might be nice to identify which identifiers you want to output.

Take the example 
```sql
SELECT PATTERN (i, e: Val1 frst _, e) FROM our_table WHERE frst > 0;
```

How do we say that we want to only use frst as a conditional in the where statement but not actually output it?

EDIT: Revised example because the first example could be accomplished without a guard.

**Comment by feffes** [comment]
<s> It might be nice to not think of the pattern as "output first" but just matches that can then be used in an output keyword

```sql
SELECT PATTERN (e: Val1 frst _) FROM our_table WHERE frst > 0 OUTPUT i, frst;
```

EDIT: This still allows for multiple matches on the same column, aka 


```sql
SELECT PATTERN (e: Val1 frst _, e: Val1 _ 69 ) FROM our_table WHERE frst > 0 OUTPUT i, frst;
```

EDIT2: But I can't think of a reason matching multiple times on the same column would ever be useful.  </s>


This is now done through selects of selects.
AKA
```sql
SELECT x, y FROM SELECT {a pattern that matches x and y and potentially more} FROM table;
```

**Comment by hulthe** [comment]
We talked a bit about type definitions, and how the type names in PSQL are alien and scary.
So how do we want to handle types in our dialect, and do we want to differentiate them from other identifiers?

First of all, i don't think we should be allowing spaces in type identifiers, like in psql. (e.g. `TIMESTAMP WITH TIMEZONE`) 

One example is to go the Haskell route, with PascalCase being used for types, forcing type names to start with a capital letter, and identifiers always starting with a lower case letter.

Another possibility is to let the user use any identifier he or she wants for types. This would allow the user to "shadow" type definitions by binding values to identifiers with the same name. If we do this we might want to use some sort of namespacing to allow using these shadowed types anyway.

Example:
```sql
-- renaming column "my_int" to INTEGER
SELECT (my_int as INTEGER) FROM table
-- INTEGER Could still be used through the global namespace:
::INTEGER
```

Another thing we definitively need to consider is the syntax for defining sum-types., simply going with the Haskell syntax might be possible (except if we allow spaces in type names, this would probably confuse the parser).

The way possible ways of defining sum-types vary in different languages, for example: in rust you can define struct-like variants of sum-types:
```rust
enum SumType {
    StructVariant {
        field_name: i32,
    },
    TupleVariant(i32, f32),
    BareVariant,
}
```

We should make sure that both ORMs and users can easily use sum-type variants like these in the database, ~although simply discarding the field names might be a good-enough workaround~.

EDIT: Actually, discarding the field names for the rust example might yield issues, since tuples are ordered, but structs aren't...

**Comment by feffes** [comment]
TTESSSt

**Comment by feffes** [comment]
test2

**Comment by hulthe** [comment]
Another thing we should decide how to handle is conflicting names of variants/constructors, e.g.
```haskell
-- Having both these definitions in the same file is an error
data SumType1 = Foo | Bar
data SumType2 = Foo | Baz
```

In Rust you mostly have to access variants through the name of the type, e.g. `SumType1::Foo` and `SumType2::Foo`. In Haskell you have to specify which constructors you need when importing them. If we want to avoid this sort of namespacing in our db we might have to go the Rust-like route.

Specifying the type along with the variant would also simplify type-checking :)

@Swexbe @feffes @Baloo1 @Arunvik @Sorchar any thoughts?

**Comment by feffes** [comment]
Is there a situation where inferring the constructor from the column type is not sufficient?

**Comment by hulthe** [comment]
We might not be in a context where we have a column type, e.g. constructing an comparing two variants in a WHERE:
```sql
SELECT goja FROM bleh WHERE Var1(1, 2, 3) == Var1(1, 2, 3)
```

The way you would normally implement type checking for an `Expr::Equals(e1, e2)` is to compute the type of `e1` and `e2` and then compare them. But if there are multiple constructors called `Var1` the type checker wouldn't know which to pick, even if both were valid.

I've been looking at the implementation of the type checker and it looks to me like cases liike these could complicate things, and we don't really want to get stuck at doing something not related to the purpose of the project.

**Comment by feffes** [comment]
We could allow inference based on the context provided by the pre-tc and require explicitly specifying for ambiguous constructors.

**Comment by Baloo1** [comment]
Inference based on context could be prone to bugs. An example scenario that should be common:

Developer 1 creates a query A.
Query A queries for type Var1 which is not ambiguous, inference succeeds. 

Developer 2 creates a new type Var2 which is ambiguous to Var1. 
Developer 2 creates a query B.
Query B queries for type Var2 which is ambiguous, inference fails (probably gives an error about inference failing, needs explicit specification), explicitly states Var2 in query.

This leaves Query A broken as it cannot inference and Developer 2 would need to understand that Query A inferences Var1. In a bigger system this quickly becomes impossible to handle for Developer 2.

**Comment by hulthe** [comment]
Me and @Swexbe toyed with the idea of moving pattern matching from the SELECT clause to the WHERE clause, since this would make the SELECT easier to look at if you're only interested in exactly what data is selected and not where the data comes from.

The problem with that is that the WHERE-clause in SQL accepts a single boolean expression, so unless we want to change that to a list of booleans and patterns (e.g. `WHERE x == 3, false, y: Var1 foo`), then patterns would have to resolve to a boolean value (true on match, false otherwise).

This might technically be possible, but then the type checker would have to handle situations where a binding in a pattern is only valid sometimes, e.g.
```sql
-- this is a type-error since "foo" might not exist in a valid column
SELECT foo FROM bar WHERE col1: Var1 foo OR col2 == 3; 

-- this is also a type-error since there might be muliple bindings of "foo"
SELECT foo FROM bar WHERE col1: Var1 foo || col3: Var1 foo;
``` 
Another solution might be to have patterns in its own clause, e.g.
```sql
SELECT foo FROM bar MATCHES col1: Var1 foo WHERE col2 == 3;
```

**Comment by hulthe** [comment]
> We might not be in a context where we have a column type, e.g. constructing an comparing two variants in a WHERE:
> 
> ```sql
> SELECT goja FROM bleh WHERE Var1(1, 2, 3) == Var1(1, 2, 3)
> ```
> 
> The way you would normally implement type checking for an `Expr::Equals(e1, e2)` is to compute the type of `e1` and `e2` and then compare them. But if there are multiple constructors called `Var1` the type checker wouldn't know which to pick, even if both were valid.
> 
> I've been looking at the implementation of the type checker and it looks to me like cases liike these could complicate things, and we don't really want to get stuck at doing something not related to the purpose of the project.

Another possible solution to the ambiguity problem with constructors is duck-typing. 🦆

`Var1(1, 2, 3)` could be treated as an "untyped" value, comparing it based on how it looks rather than what type is has. The value could then be checked as a valid instance of a specific type when/if it needs to be, e.g. if it is inserted in, or compared to, a table column.
```sql
SELECT goja FROM bleh WHERE Var1(1, 2, 3) == Var1(1, 2, 3)
```

This might enable other possibly undesired behaviors though...
